### ISSUE TITLE
Web Installer Does Not Reuse Existing Download, Same Version, On Re-Install

### ISSUE THREAD

**Issue by johnywhy** [elixir-lang/elixir-windows-setup#11]
hi

after receiving [this error](https://github.com/elixir-lang/elixir-windows-setup/issues/10), i had to run the installer again. 

It downloaded all over again. This was moments after the first attempt. 

I have a slow connection, and took forever, both times!

Plz re-use existing download, if same version. 

thx!

**Comment by josevalim** [comment]
Closing this as we likely won't have time to focus on it and redownloading can be desired on corrupted installs.
