### ISSUE TITLE
Wrong Erl version

### ISSUE THREAD

**Issue by AndreVarandas** [elixir-lang/elixir-windows-setup#12]
Hi, I am not able to run run elixir commands after installing,  (Wrong Erl Version with installer?)

Steps: 

- Install choosing the version 1.5.1 (latest) - it installs **Erlang 9.0**.
- Try to run any command like `elixir --version` or open `iex` and it will search for erl 8.2

![imagem](https://user-images.githubusercontent.com/11405075/29813401-deb27b68-8ca1-11e7-9cea-f9c7ead5f386.png)

**Comment by OvermindDL1** [comment]
Did you upgrade erlang 'after' you installed Elixir?  Elixir needs to be installed after erlang so it knows all it's paths.l  If you reinstall elixir then it should pick up the new erlang install fine.

**Comment by AndreVarandas** [comment]
Hi, thanks for your response,

Im sorry, my bad, I had this older version installed and perhaps poorly uninstalled some time ago. Messed all up... Now, chosing the right folder, all clean, it works like a charm. 👍
