### ISSUE TITLE
Missing support for proxy in web installer

### ISSUE THREAD

**Issue by magynhard** [elixir-lang/elixir-windows-setup#13]
When using a proxy, which is often used in companies, the web installer can not download the packages.

The only workaround is to download the packages manually and set the path variables.

It would be nice, if the setup can consider the system proxy settings automatically or provide an option to set the proxy manually. For example by choosing a radio button "use proxy" and text input fields to type in the proxy settings.

**Comment by josevalim** [comment]
Agreed. A contribution would be very appreciated here!

**Comment by chyndman** [comment]
In [version 2.3](https://github.com/elixir-lang/elixir-windows-setup/releases/tag/v2.3) we use Inno Setup's builtin download functionality now. Although I can't test a proxy myself, the Inno Setup documentation claims proxy settings are used. So I'll presume this works now.
