### ISSUE TITLE
Elixir installer should switch from getting otp from erlang.org since the site is very, very slow

### ISSUE THREAD

**Issue by amoh-godwin** [elixir-lang/elixir-windows-setup#17]
### Environment

* Operating system: Windows 10

### Current behavior

OTP from erlang.org is way too slow.
The speed can put someone off from installing
![elixir_installer](https://user-images.githubusercontent.com/18188576/105062526-99522080-5a72-11eb-8bef-4847fab44458.jpg)

### Expected behavior
Please use their GitHub release links instead. It is **safer**
eg: https://github.com/erlang/otp/releases/download/OTP-23.2.2/otp_win64_23.2.2.exe

**Comment by jeffrey-kor** [comment]
Thank you :)
After installation, Can I do any thing more to complete installation?
I want to code using elixir and phenix. thank you again!

**Comment by amoh-godwin** [comment]
No, I am not sure.

**Comment by amoh-godwin** [comment]
YOu should be able to do
`elixir --version`
If you can't, then you should add Elixir to your PATH: https://elixir-lang.org/install.html#setting-path-environment-variable

**Comment by jeffrey-kor** [comment]
YES! Thanks to your efforts, finally I can compile my code in local :>

**Comment by amoh-godwin** [comment]
Good to hear that @jeffrey-kor

**Comment by josevalim** [comment]
We have migrated to GitHub ones. Thank you!
