### ISSUE TITLE
Elixir 1.12 is getting blocked by pihole

### ISSUE THREAD

**Issue by stonetwig** [elixir-lang/elixir-windows-setup#19]
![image](https://user-images.githubusercontent.com/47466/119330276-543f3480-bc86-11eb-8967-39427db07017.png)

I had to whitelist `crl4.digicert.com` in order for the download to work.
A lot of people uses pihole and probably not everyone will realize that this is the issue.

Don't know if you want / can do anything about it, but maybe a suggestion would be to look into the issue.
The main blocklist used (Gravity) was the one blocking it.

**Comment by ericmj** [comment]
The `Precompiled.zip` [1] file is hosted by GitHub, so please raise the issue with GitHub or the maintainers of the blocklist.

[1] https://github.com/elixir-lang/elixir/releases/download/v1.12.0/Precompiled.zip

**Comment by stonetwig** [comment]
Ok, thanks for the quick reply. I will be raising it with the maintainers of the blocklist.
