### ISSUE TITLE
Prebuilt Windows offline installer

### ISSUE THREAD

**Issue by ccverak** [elixir-lang/elixir-windows-setup#2]
Can you please release a pre-built elixir offline installer for windows?, its a good choice for those with low internet connections.

**Comment by chyndman** [comment]
[Here](https://onedrive.live.com/redir?resid=710348382B4EA94!374581&authkey=!AB_3Cife6mOtAUg&ithint=file%2cexe) is an offline installer for v1.1.1.  I threw it together by:

1. Running `elixir-websetup.exe`
2. Click next.
3. Click next.
4. Uncheck "Install Erlang"
5. Click next.
6. Click next.
7. Wait for the web installer to compile the offline installer.
8. Close the offline installer.
9. Navigate to %temp% in File Explorer
10. Look in each folder starting with `is-` for `Output\elixir-v1.1.1-setup.exe`

This of course can be done by anyone, although the resulting installer is unsigned and won't show a welcome page.  I'll leave it up to @josevalim to decide whether we should provide (signed) offline installers going forward.

**Comment by josevalim** [comment]
@ccverak we don't plan to support offline installers because they add more complexity to our release cycles. Fortunately, you can use precompiled Elixir. All you really need to install Elixir is to add the executable to your PATH. More information on elixir-lang.org/install.html
