### ISSUE TITLE
Error with Erlang/OTP 25.0.2

### ISSUE THREAD

**Issue by ducdetronquito** [elixir-lang/elixir-windows-setup#23]
Hi !

I wanted to give Elixir a try this weekend on my windows machine, so I installed Erlang/OTP 25.0.2 (via the windows installer), and installed Elixir (1.13.4) following [the installation steps](https://elixir-lang.org/install.html#windows).

When trying to install the [Phoenix application generator](https://hexdocs.pm/phoenix/installation.html#phoenix), I ran into the following error:

```bash
mix archive.install hex phx_new

Error while loading project :mix_local_installer at c:/Users/giomee/AppData/Local/Temp/mix-local-installer-fetcher-wZJPHw

12:35:31.537 [error] Loading of c:/Program Files (x86)/Elixir/lib/elixir/ebin/Elixir.Code.Formatter.beam failed: :badfile


12:35:31.528 [error] beam\beam_load.c(86): Error loading module 'Elixir.Code.Formatter':
  lambda already defined for label 749. To fix this, please recompile this module with an OTP 25 compiler.


** (UndefinedFunctionError) function Code.Formatter.locals_without_parens/0 is undefined (module Code.Formatter is not available)
    (elixir 1.13.4) Code.Formatter.locals_without_parens()
    (elixir 1.13.4) lib/code/normalizer.ex:22: Code.Normalizer.normalize/2
    (elixir 1.13.4) lib/code.ex:1107: Code.quoted_to_algebra/2
``` 

I think @josevalim answer on this issue (https://github.com/elixir-lang/elixir/issues/11220#issuecomment-1130144452) could be the answer, but I'm not sure. 

Have a nice day :)

Ps: My apologies if this issue does not belong to this repository !

**Comment by josevalim** [comment]
Yes, this is being tracked already. It will be fixed in the next release. You need to use Erlang/OTP 24 for now or compile Elixir yourself. :)

**Comment by ducdetronquito** [comment]
Thanks for the quick reply, and good luck for the next release :)
