### ISSUE TITLE
Elixir v1.14 init terminating in do_boot

### ISSUE THREAD

**Issue by sysmat** [elixir-lang/elixir-windows-setup#24]
- using elixir-websetup.exe
- it installed _C:\Program Files\erl-24.0\bin_
- it installed _C:\Program Files (x86)\Elixir\bin_
- when runninh: `elixir help` 
```json
{"init terminating in do_boot",{undef,[{elixir,start_cli,[],[]},{init,start_em,1,[{file,"init.erl"},{line,1190}]},{init,do_boot,3,[{file,"init.erl"},{line,888}]}]}}
init terminating in do_boot ({undef,[{elixir,start_cli,[],[]},{init,start_em,1,[{_},{_}]},{init,do_boot,3,[{_},{_}]}]})
```
- Crash dump is being written to: erl_crash.dump...done, I can't upload it github dosen't support it

**Comment by josevalim** [comment]
Closing as it has been opened on Elixir repo as well.
