### ISSUE TITLE
Error with 1.14

### ISSUE THREAD

**Issue by meatball133** [elixir-lang/elixir-windows-setup#25]
Get following error when trying to install elixir 1.14 or 1.14.1:
```
{"init terminating in do_boot",{undef,[{elixir,start_cli,[],[]},{init,start_em,1,[{file,"init.erl"},{line,1211}]},{init,do_boot,3,[{file,"init.erl"},{line,909}]}]}}
init terminating in do_boot ({undef,[{elixir,start_cli,[],[]},{init,start_em,1,[{_},{_}]},{init,do_boot,3,[{_},{_}]}]})
```

**Comment by josevalim** [comment]
What is your Erlang version? Can you try OTP 25 or later?

**Comment by meatball133** [comment]
That fixed it, although would probably be nice with a bit better error message.

**Comment by josevalim** [comment]
@meatball133 PR submitted here to improve the error messages :) https://github.com/erlang/otp/pull/6372
