### ISSUE TITLE
Still no v1.14.2 in the web setup?

### ISSUE THREAD

**Issue by makarichevss** [elixir-lang/elixir-windows-setup#26]
Hi !
Elixir v1.14.2 was released 3 days ago, but the latest version in the web setup file for Windows is 1.14.1.
Have Erlang OTP 25 installed.

![2022-11-14_031248](https://user-images.githubusercontent.com/62963044/201552073-83a8524b-bac2-4f7c-8d70-4a63efa42637.jpg)

**Comment by josevalim** [comment]
Done!
