### ISSUE TITLE
Version 2.4 cannot continue

### ISSUE THREAD

**Issue by multi422** [elixir-lang/elixir-windows-setup#29]
![image](https://user-images.githubusercontent.com/124760226/227809966-f9c63d41-e868-4e36-8d69-c206a9967590.png)

When I open elixir-webstep.exe, this error message is displayed.
How can I fix it?

**Comment by josevalim** [comment]
Can you access the file directly from your browser or command line?

**Comment by multi422** [comment]
How can I access the file directly from my browser?
I tried installation using "choco install elixir", but erlang installation as a dependency failed.

**Comment by josevalim** [comment]
Just try accessing https://elixir-lang.org/elixir.csv directly to rule out any issues. Did you try choco install erlang as well?

**Comment by multi422** [comment]
Thanks for your help.
I can access https://elixir-lang.org/elixir.csv and have already downloaded it.
I just tried choco install elixir.
![image](https://user-images.githubusercontent.com/124760226/227811240-2c556b8b-876b-46cd-a90e-083a7a43df2e.png)

**Comment by josevalim** [comment]
If you try `choco install Erlang`, does it report any error? Which error did you get installing Elixir?

**Comment by multi422** [comment]
I didn't try choco install Erlang, "choco install elixir"  installs erlang as a dependency.
but erlang installation has failed because of timeout error.
So I tried to downloaded erlang installer from "https://www.erlang.org/downloads" and installed erlang using it.

**Comment by josevalim** [comment]
So if both Erlang and Elixir are failing to download, I would assume there is something else going on here. :/

**Comment by multi422** [comment]
Can I install elixir using elixir-websetup.exe at this point?

**Comment by multi422** [comment]
Anyway, thanks for your help, Jose.
I just tried to install erlang using erlang installer I downloaded manually from erlang.org. And I installed elixir using chocolatey.
The elixir installation has been done successfully.
```
C:\Users\Administrator>elixir -v
Erlang/OTP 25 [erts-13.2] [source] [64-bit] [smp:12:12] [ds:12:12:10] [async-threads:1] [jit:ns]

Elixir 1.14.3 (compiled with Erlang/OTP 25)
```
I think elixir-websetup.exe has some issues now.
