### ISSUE TITLE
Wrong path variable entered when x86 install chosen for ErlangOTP

### ISSUE THREAD

**Issue by morr0350** [elixir-lang/elixir-windows-setup#31]
When using the Windows Installer, on Windows 11, I chose the x86 installation for Erlang/OTP in the installation dialog.  It correctly installed the x86 version, however, the path that was entered in my environment variables was "C:\Program Files\Erlang OTP\bin", which would be the path if it were the 64-bit version.  It was easy to solve by editing the path to "C:\Program Files (x86)\Erlang OTP\bin", but the error you get from elixir is a bit cryptic when it can't find the erlang binaries!  ({"init terminating in do_boot".....etc etc).

I think what may have been a factor is that I had a very old forgotten 64-bit install of erlang in Program Files with a different directory naming convention (C:\Program Files\erlang) than the current "Erlang OTP" convention.  Maybe the Windows registry key still matched for the old install and the installer thought it should go ahead and create a 64-bit path variable but with the new naming convention "Erlang OTP"?

Perhaps it is working as designed and I should have made sure to uninstall previous Erlang versions, but either way, "C:\Program Files\Erlang OTP\bin" was not a correct Path variable since that directory did not exist after install.

**Comment by morr0350** [comment]
Perhaps this is a duplicate of https://github.com/elixir-lang/elixir-windows-setup/issues/28 and I should have properly uninstalled previous Erlang versions before running the installer.  Feel free to close if this is just a duplicate, as for me, updating my path corrected the issue, but entirely uninstalling the old erlang version and reinstalling elixir also likely would've had the same effect.

**Comment by chyndman** [comment]
Thanks for reporting nonetheless. Unfortunately we rely on the registry for detecting Erlang - and that ends as well as you'd expect for the registry ;).
