### ISSUE TITLE
Installer Should Pull Latest Version Of Erlang Available

### ISSUE THREAD

**Issue by OnorioCatenacci** [elixir-lang/elixir-windows-setup#4]
I just tried installing elixir via the installer on a clean Win 10 VM. It worked exactly as expected except for one thing. Rather than pulling the latest version of Erlang available which meets the requirement (as of now 18.2.1) it pulled the minimum version which meets the requirement (18.1).  18.1 would be the least version that would be ok but if there's a higher version available that should be used.

I can take a look at the code and see if I can manage to make the change but I'm reporting this issue so it won't get forgotten.

**Comment by josevalim** [comment]
This is on me. We keep the erlang versions here: https://github.com/elixir-lang/elixir-lang.github.com/blob/master/erlang.csv

**Comment by OnorioCatenacci** [comment]
Oh--ok.  I see what you're saying.  I'll make a pull request.

--
Onorio


On Wed, Jan 27, 2016 at 11:14 AM, José Valim <notifications@github.com>
wrote:

> This is on me. We keep the erlang versions here:
> https://github.com/elixir-lang/elixir-lang.github.com/blob/master/erlang.csv
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/elixir-lang/elixir-windows-setup/issues/4#issuecomment-175717859>
> .
>



-- 
Onorio Catenacci

http://onor.io
http://www.google.com/+OnorioCatenacci
