### ISSUE TITLE
Installer Should Install x64 Versions On 64 Bit OS

### ISSUE THREAD

**Issue by OnorioCatenacci** [elixir-lang/elixir-windows-setup#5]
I just installed on a clean Win 10 VM which is 64 bit. But the installer pulled the x86 version of Erlang and likewise put the Elixir commands etc. into the Program Files (x86) dir.  The installer should detect that it's installing on a 64-Bit OS and act appropriately (either automatically installing the x64 version or offering the user the choice). 

Again, I'll see if I can generate a PR; just wanted to record this so it's not forgotten.

**Comment by josevalim** [comment]
perfect, this would be appreciated. :)

**Comment by chyndman** [comment]
On my 64-bit W10 system I see that the 64-bit Erlang option is available and automatically selected on [the appropriate page on the installer](http://imgur.com/v2DY8gw).  Do you not see this screen or does it install the 32-bit version regardless?

As for Elixir, the [Inno Setup documentation](http://www.jrsoftware.org/ishelp/index.php?topic=setup_architecturesinstallin64bitmode) recommends against installing as a 64-bit application unless there are 64-bit binaries being installed.  So Elixir will always install in "Program Files (x86)" by default regardless of Erlang.

**Comment by OnorioCatenacci** [comment]
Hi Chris,

I'll double check.  I think it installed the x86 version but I may have
missed it. Its easy for me to double check so I'll do so and post a comment
when I'm sure.

Thanks!

--
Onorio


On Wed, Jan 27, 2016 at 11:33 AM, Chris Hyndman <notifications@github.com>
wrote:

> On my 64-bit W10 system I see that the 64-bit Erlang option is available
> and automatically selected on the appropriate page on the installer
> <http://imgur.com/v2DY8gw>. Do you not see this screen or does it install
> the 32-bit version regardless?
>
> As for Elixir, the Inno Setup documentation
> <http://www.jrsoftware.org/ishelp/index.php?topic=setup_architecturesinstallin64bitmode>
> recommends against installing as a 64-bit application unless there are
> 64-bit binaries being installed. So Elixir will always install in "Program
> Files (x86)" by default regardless of Erlang.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/elixir-lang/elixir-windows-setup/issues/5#issuecomment-175729452>
> .
>



-- 
Onorio Catenacci

http://onor.io
http://www.google.com/+OnorioCatenacci

**Comment by OnorioCatenacci** [comment]
Ok, so the Erlang install does offer the option of installing x64.  It does default to x86 even on my x64 version of Windows but that's a minor inconvenience. 

But I'm not following you on the point about always installing in "Program Files (x86)". Is the precompiled.zip file always a 32 bit version of the files?

**Comment by chyndman** [comment]
Basically yes.  More specifically, since everything in Elixir (as far as I know) is delivered as BEAM bytecode, there are no native 64-bit binaries since there are no native binaries of any kind.  So I trust Inno Setup's judgement to install as a 32-bit application out of convention.

**Comment by OnorioCatenacci** [comment]
Ok, I can see the reasonableness of that.  But if someone installs the
Erlang RT as x64 then is the BEAM bytecode effectively being run x64 or is
it x86?  I mean I don't think it matters which directory it's in because
the bytecode is whatever it is.  But if someone chooses to install Erlang
as x64 and then Elixir is installed as x86 regardless would that
potentially cause confusion?

It's probably a moot question anyway since if people found it confusing
they would have already said something on the mailing list or on twitter or
someplace.  So I guess this issue can just be closed.

On Wed, Jan 27, 2016 at 7:07 PM, Chris Hyndman <notifications@github.com>
wrote:

> Basically yes. More specifically, since everything in Elixir (as far as I
> know) is delivered as BEAM bytecode, there are no native 64-bit binaries
> since there are no native binaries of any kind. So I trust Inno Setup's
> judgement to install as a 32-bit application out of convention.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/elixir-lang/elixir-windows-setup/issues/5#issuecomment-175919578>
> .
>



-- 
Onorio Catenacci

http://onor.io
http://www.google.com/+OnorioCatenacci

**Comment by josevalim** [comment]
Yes, Elixir does not care about being a x86 or a x64 install. It is all the same.

**Comment by OnorioCatenacci** [comment]
Closing this issue since it seems to be a simple misunderstanding on my part.
