### ISSUE TITLE
Latest Elixir version installed regardless of selection

### ISSUE THREAD

**Issue by chyndman** [elixir-lang/elixir-windows-setup#8]
Continuation of elixir-lang/elixir#5616.

**Comment by idahogray** [comment]
I can confirm this issue exists. I also attempted to defer installation and it still builds the 1.4 installer not matter which release I choose.

**Comment by chyndman** [comment]
@KeeperB5 @idahogray the latest installer release ([v2.1](https://github.com/elixir-lang/elixir-windows-setup/releases/tag/v2.1)) should fix this; please let me know if that's the case.

**Comment by KeeperB5** [comment]
Original issue has been fixed. However, Windows 10 complains about unknown publisher when launching the installer. This didn't happen with previous version of the installer.

**Comment by chyndman** [comment]
That's due to how SmartScreen works; the filename "elixir-websetup.exe" is usually downloaded from the Elixir website and not GitHub, so SmartScreen wants you to believe it's a malicious file.

**Comment by josevalim** [comment]
Thank you @chyndman! We will update the Elixir website with the new installer soon. :heart:

**Comment by idahogray** [comment]
I can confirm that choosing 1.3.4 and Defer Installation creates a 1.3.4 installation package. Thanks @chyndman .
